language: objective-c

before_script:
  - gem uninstall -Vax --force --no-abort-on-dependent calabash-cucumber
  - gem uninstall -Vax --force --no-abort-on-dependent run_loop
  - script/ci/travis/clone-and-install-run-loop.rb
  - script/ci/travis/install-gem-libs.rb
  - script/ci/travis/bundle-install.rb
  - gem install json

script:
  - script/ci/travis/install-gem-ci.rb
  - script/ci/travis/rspec-ci.rb
  - script/ci/travis/unit-ci.rb
  - script/ci/travis/rake-build-server-ci.rb
  - script/ci/travis/cucumber-ci.rb --tags ~@no_ci

rvm:
  - 1.9.3
  - 2.1.0
  - 2.1.1

notifications:
  email:
    on_success: change
    on_failure: always

