#!/usr/bin/env bash

TRAVIS_PROVISIONING_PROFILE="${PWD}/${TRAVIS_PROVISIONING_PROFILE}"

cd calabash-cucumber
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

# Enable binaries to be installed.
#
# calabash-cucumber at /Users/travis/build/calabash/calabash-ios/calabash-cucumber did not have a valid gemspec.
# This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
# The validation message from Rubygems was:
#  ["staticlib/calabash.framework.zip"] are not files
touch calabash.framework
zip -r calabash.framework.zip calabash.framework
mkdir -p staticlib
mv calabash.framework.zip staticlib/
rm calabash.framework

gem install --no-document bundler
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to install bundler"
    exit $RETVAL
else
    echo "INFO: installed bundler"
fi

bundle install
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to bundle install"
    exit $RETVAL
else
    echo "INFO: bundled"
fi

# rspec tests
# bundle exec rake spec
# RETVAL=$?
# if [ $RETVAL != 0 ]; then
#     echo "FAIL: failed rspec tests"
#     exit $RETVAL
# else
#     echo "INFO: passed rspec tests"
# fi

# on-simulator smoke tests against jmoody/calabash-ios-example fork
rm -rf calabash-ios-example
git clone https://github.com/jmoody/calabash-ios-example

cd calabash-ios-example

set +o errexit
git checkout -b test/workspace "origin/${TRAVIS_BRANCH}"
RETVAL=$?
set -o errexit

if [ $RETVAL != 0 ]; then
    echo "WARN: skipping simulator tests and XTC job!"
    echo "WARN: $TRAVIS_BRANCH does not exist on jmoody/calabash-ios-example repository"
    echo "WARN: exiting success without simulator tests and XTC job."
    exit 0
fi

# exhaustive on-simulator smoke tests
# ./run-tests.sh
# RETVAL=$?
# if [ $RETVAL != 0 ]; then
#     echo "FAIL: failed calabash-ios-example smoke tests"
#     exit $RETVAL
# else
#     echo "INFO: passed calabahs-ios-example smoke tests"
# fi

bundle install

XAMARIN_DIR="${PWD}/xtc-staging"

echo "INFO: creating the ./xtc-staging directory"
rm -rf "${XAMARIN_DIR}"
mkdir -p "${XAMARIN_DIR}"

echo "INFO: copying features over to ${XAMARIN_DIR}"
cp -r features "${XAMARIN_DIR}/"

echo "INFO: installing config/xtc-profiles.yml to ${XAMARIN_DIR}/cucumber.yml"
cp "./config/xtc-profiles.yml" "${XAMARIN_DIR}/cucumber.yml"

TARGET_NAME="LPSimpleExample-cal"
XC_PROJECT="LPSimpleExample.xcodeproj"
XC_SCHEME="${TARGET_NAME}"
CAL_BUILD_CONFIG=Debug
CAL_BUILD_DIR="${PWD}/build/jenkins"
rm -rf "${CAL_BUILD_DIR}"
mkdir -p "${CAL_BUILD_DIR}"

set +o errexit

xcodebuild \
    -derivedDataPath "${CAL_BUILD_DIR}" \
    -project "${XC_PROJECT}" \
    -scheme "${TARGET_NAME}" \
    -sdk iphoneos \
    -configuration "${CAL_BUILD_CONFIG}" \
    clean build # | $RBENV_EXEC bundle exec xcpretty -c

RETVAL=$?
#RETVAL=${PIPESTATUS[0]}

set -o errexit

if [ $RETVAL != 0 ]; then
    echo "FAIL:  build step failed"
    exit $RETVAL
fi

set +o errexit

APP_BUNDLE_PATH="${CAL_BUILD_DIR}/Build/Products/${CAL_BUILD_CONFIG}-iphoneos/${TARGET_NAME}.app"
IPA_PATH="${XAMARIN_DIR}/{TARGET_NAME}.ipa"
set -o errexit

xcrun -sdk iphoneos PackageApplication -v "${PWD}/${APP_BUNDLE_PATH}" -o "${XAMARIC}/${IPA_PATH}" --sign "${TRAVIS_CODESIGNING_DEVELOPER}" --embed "${TRAVIS_PROVISIONING_PROFILE}"

RETVAL=$?

if [ $RETVAL != 0 ]; then
    echo "FAIL:  package step failed"
    exit $RETVAL
fi

cp Gemfile "${XAMARIN_DIR}/Gemfile"
cd "${XAMARIN_DIR}"

gem install xamarin-test-cloud
test-cloud submit LPSimpleExample-cal.ipa ${XTC_API_TOKEN} -d ${XTC_DEVICE_SET} -c cucumber.yml -p default

exit 0
