#!/usr/bin/env bash

cd calabash-cucumber
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

# Enable binaries to be installed.
#
# calabash-cucumber at /Users/travis/build/calabash/calabash-ios/calabash-cucumber did not have a valid gemspec.
# This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
# The validation message from Rubygems was:
#  ["staticlib/calabash.framework.zip"] are not files
touch calabash.framework
zip -r calabash.framework.zip calabash.framework
mkdir -p staticlib
mv calabash.framework.zip staticlib/
rm calabash.framework

gem install --no-document bundler
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to install bundler"
    exit $RETVAL
else
    echo "INFO: installed bundler"
fi

bundle install
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to bundle install"
    exit $RETVAL
else
    echo "INFO: bundled"
fi

# rspec tests
# bundle exec rake spec
# RETVAL=$?
# if [ $RETVAL != 0 ]; then
#     echo "FAIL: failed rspec tests"
#     exit $RETVAL
# else
#     echo "INFO: passed rspec tests"
# fi

# on-simulator smoke tests against jmoody/calabash-ios-example fork
cd test/cucumber

bundle install --local

# remove any stale targets
bundle exec calabash-ios sim reset

# Disable exiting on error so script continues if tests fail
set +o errexit

export APP_BUNDLE_PATH="./LPSimpleExample-cal.app"

RETVAL=0

bundle exec cucumber -p sim61_4in           $CUCUMBER_ARGS
RETVAL=$(($RETVAL+$?))
# $RBENV_EXEC bundle exec cucumber -p sim71_4in          -f json -o ci-reports/calabash/iphone-71-4in.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))

# # Will not pass on travis although a similar rspec test does.
# # Instead we run on the 4in 7.0 64 bit simulator.
# if [ -z $TRAVIS ]; then
#     $RBENV_EXEC bundle exec cucumber -p sim71_64b          -f json -o ci-reports/calabash/iphone-71-4in-64b.json $CUCUMBER_ARGS
#     RETVAL=$(($RETVAL+$?))
# else
#     $RBENV_EXEC bundle exec cucumber -p sim70_64b          -f json -o ci-reports/calabash/iphone-70-4in-64b.json $CUCUMBER_ARGS
#     RETVAL=$(($RETVAL+$?))
# fi

# $RBENV_EXEC bundle exec cucumber -p sim61r             -f json -o ci-reports/calabash/iphone-61-3.5in.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))
# $RBENV_EXEC bundle exec cucumber -p sim71r             -f json -o ci-reports/calabash/iphone-71-3.5in.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))

# $RBENV_EXEC bundle exec cucumber -p sim61_ipad_r       -f json -o ci-reports/calabash/ipad-61.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))
# $RBENV_EXEC bundle exec cucumber -p sim71_ipad_r       -f json -o ci-reports/calabash/ipad-71.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))
# $RBENV_EXEC bundle exec cucumber -p sim71_ipad_r_64b   -f json -o ci-reports/calabash/ipad-71-64b.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))

# $RBENV_EXEC bundle exec cucumber -p sim61_sl           -f json -o ci-reports/calabash/ipad-61-no-instruments.json $CUCUMBER_ARGS
# RETVAL=$(($RETVAL+$?))

set -o errexit

if [ $RETVAL != 0 ]; then
    echo "FAIL: failed $RETVAL out of 9 simulators"
fi

#gem install xamarin-test-cloud
#test-cloud submit LPSimpleExample-cal.ipa ${XTC_API_TOKEN} -d ${XTC_DEVICE_SET} -c xtc-profiles.yml -p default

exit 0
