#!/usr/bin/env bash

cd calabash-cucumber
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

# Enable binaries to be installed.
#
# calabash-cucumber at /Users/travis/build/calabash/calabash-ios/calabash-cucumber did not have a valid gemspec.
# This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
# The validation message from Rubygems was:
#  ["staticlib/calabash.framework.zip"] are not files
touch calabash.framework
zip -r calabash.framework.zip calabash.framework
mkdir -p staticlib
mv calabash.framework.zip staticlib/
rm calabash.framework

gem install --no-document bundler
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to install bundler"
    exit $RETVAL
else
    echo "INFO: installed bundler"
fi

bundle install
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to bundle install"
    exit $RETVAL
else
    echo "INFO: bundled"
fi

# bundle exec rake spec
# RETVAL=$?
# if [ $RETVAL != 0 ]; then
#     echo "FAIL: failed rspec tests"
#     exit $RETVAL
# else
#     echo "INFO: passed rspec tests"
# fi

rm -rf calabash-ios-example
git clone https://github.com/jmoody/calabash-ios-example
cd calabash-ios-example
./run-tests.sh
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed calabash-ios-example smoke tests"
    exit $RETVAL
else
    echo "INFO: passed calabahs-ios-example smoke tests"
fi

exit 0
