#!/usr/bin/env bash

CALABASH_REPO_PATH="${PWD}"

cd calabash-cucumber

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

../script/shared-bundler-tasks.sh

rm -rf .bundle
rm -rf vendor

if [ -z $TRAVIS ]; then
    bundle install --no-deployment
else
    bundle install --deployment
fi

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to bundle install"
    exit $RETVAL
else
    echo "INFO: bundled"
fi

#if [ -z $TRAVIS ]; then
#    bundle exec rake install
#    RETVAL=$?
#else
#    rake install
#    RETVAL=$?
#fi

bundle exec rake install

if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to calabash-cucumber gem"
    exit $RETVAL
fi

CALABASH_VERSION=`bundle exec calabash-ios version | tr -d '\n'`
if [ -z $CALABASH_VERSION ]; then
    echo "FAIL: could not find the calabash-cucumber gem version"
    exit 1
fi

# this is really and truly travis-ci and not the local env
if [ ! -z $HAS_JOSH_K_SEAL_OF_APPROVAL ]; then
    bundle config local.calabash-cucumber ${CALABASH_REPO_PATH}
    bundle config disable_local_branch_check true
fi

cd test/cucumber
rm -rf Gemfile
rm -rf Gemfile.lock
rm -rf .bundle
rm -rf vendor

echo $CALABASH_VERSION
echo "source 'http://rubygems.org'" > Gemfile

# this is really and truly travis-ci and not the local env
if [ ! -z $HAS_JOSH_K_SEAL_OF_APPROVAL ]; then
    echo "gem 'calabash-cucumber', :github => 'jmoody/calabash-cucumber'" >> Gemfile
else
    echo "gem 'calabash-cucumber', '$CALABASH_VERSION'" >> Gemfile
fi

gem install --no-document xamarin-test-cloud
test-cloud submit LPSimpleExample-cal.ipa ${XTC_API_TOKEN} -d ${XTC_DEVICE_SET} -c config/xtc-profiles.yml -p default --series "travis-ci"

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: XTC job failed."
    exit $RETVAL
fi

exit $RETVAL
