#!/usr/bin/env bash

cd calabash-cucumber

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to change directory to calabash-cucumber - should called as 'script/ci'"
    exit $RETVAL
else
    echo "INFO: changed directory to ${PWD}"
fi

# Enable binaries to be installed.
#
# calabash-cucumber at /Users/travis/build/calabash/calabash-ios/calabash-cucumber did not have a valid gemspec.
# This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
# The validation message from Rubygems was:
#  ["staticlib/calabash.framework.zip"] are not files
touch calabash.framework
zip -r calabash.framework.zip calabash.framework
mkdir -p staticlib
mv calabash.framework.zip staticlib/
rm calabash.framework

rm -rf *.gem
gem build calabash-cucumber.gemspec
gem install *.gem --no-document

if [ $RETVAL != 0 ]; then
    echo "FAIL: failed to calabash-cucumber gem"
    exit $RETVAL
fi

CALABASH_VERSION=`calabash-ios version | tr -d '\n'`
if [ -z $CALABASH_VERSION ]; then
    echo "FAIL: could not find the calabash-cucumber gem version"
    exit 1
fi

cd test/cucumber
rm -rf Gemfile
rm -rf Gemfile.lock
rm -rf .bundle
rm -rf vendor

echo "source 'http://rubygems.org'" > Gemfile
echo "gem 'calabash-cucumber', '$CALABASH_VERSION'" >> Gemfile

echo "Wrote Gemfile as:"
echo "$(cat Gemfile)"
echo ""

gem install --no-document xamarin-test-cloud
test-cloud submit LPSimpleExample-cal.ipa ${XTC_API_TOKEN} -d ${XTC_DEVICE_SET} -c config/xtc-profiles.yml -p default --series "travis-ci"

RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "FAIL: XTC job failed."
    exit $RETVAL
fi

exit $RETVAL
